---
# Homelab Services Dashboard

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_JELLYFIN_HOST}}:8096
        description: Media Server
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_JELLYFIN_HOST}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}

    - Jellyseerr:
        icon: jellyseerr.png
        href: http://{{HOMEPAGE_VAR_JELLYFIN_HOST}}:5055
        description: Media Requests

- Storage:
    - Open Media Vault:
        icon: openmediavault.png
        href: http://{{HOMEPAGE_VAR_PI5_HOST}}
        description: NAS Management

    - Duplicati:
        icon: duplicati.png
        href: http://{{HOMEPAGE_VAR_PI5_HOST}}:8200
        description: Backup System

- Management:
    - Portainer:
        icon: portainer.png
        href: https://{{HOMEPAGE_VAR_PI5_HOST}}:9443
        description: Container Management
        widget:
          type: portainer
          url: https://{{HOMEPAGE_VAR_PI5_HOST}}:9443
          env: 1
          key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

    - Traefik:
        icon: traefik.png
        href: http://{{HOMEPAGE_VAR_JELLYFIN_HOST}}:8080
        description: Reverse Proxy
        widget:
          type: traefik
          url: http://{{HOMEPAGE_VAR_JELLYFIN_HOST}}:8080

    - Grafana:
        icon: grafana.png
        href: http://{{HOMEPAGE_VAR_PI5_HOST}}:3001
        description: Monitoring Dashboard

- CI/CD:
    - Woodpecker CI:
        icon: woodpecker-ci.png
        href: http://{{HOMEPAGE_VAR_PI4_HOST}}:8000
        description: CI/CD Pipeline

    - Docker Registry:
        icon: docker.png
        href: http://{{HOMEPAGE_VAR_PI4_HOST}}:5000
        description: Container Registry
